# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_test(self):
        # Test name: test
        # Step # | name | target | value
        # 1 | open | /index.php | 
        self.driver.get("https://course.ncku.edu.tw/index.php")
        # 2 | setWindowSize | 1552x928 | 
        # self.driver.set_window_size(1552, 928)
        # 3 | click | linkText=登入 | 
        self.driver.find_element(By.LINK_TEXT, "登入").click()
        # 4 | type | id=user_id | P76124605
        self.driver.find_element(By.ID, "user_id").send_keys("P76124605")
        # 5 | type | id=passwd | Aa492357816
        self.driver.find_element(By.ID, "passwd").send_keys("Aa492357816")
        # 6 | click | css=.input-group:nth-child(1) | 
        self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(1)").click()
        # 7 | click | css=.input-group:nth-child(4) | 
        self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(4)").click()
        # 8 | click | id=code | 
        self.driver.find_element(By.ID, "code").click()
        # 9 | click | css=.click | 
        self.driver.find_element(By.CSS_SELECTOR, ".click").click()
        # 10 | click | id=code | 
        self.driver.find_element(By.ID, "code").click()
        # 11 | type | id=code | 2773
        self.driver.find_element(By.ID, "code").send_keys("2773")
        # 12 | click | css=#submit_by_acpw > span | 
        self.driver.find_element(By.CSS_SELECTOR, "#submit_by_acpw > span").click()
        # 13 | click | linkText=課程查詢 | 
        self.driver.find_element(By.LINK_TEXT, "課程查詢").click()
        # 14 | click | css=.btn-warning | 
        self.driver.find_element(By.CSS_SELECTOR, ".btn-warning").click()
        # 15 | click | css=.btn_menu:nth-child(1) | 
        self.driver.find_element(By.CSS_SELECTOR, ".btn_menu:nth-child(1)").click()
        # 16 | click | css=.form-group:nth-child(1) li:nth-child(2) | 
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) li:nth-child(2)").click()
        # 17 | click | css=.ui-choose > li:nth-child(8) | 
        self.driver.find_element(By.CSS_SELECTOR, ".ui-choose > li:nth-child(8)").click()
        # 18 | click | css=.btn_send | 
        self.driver.find_element(By.CSS_SELECTOR, ".btn_send").click()
        # 19 | click | css=.ui-choose > li:nth-child(5) | 
        self.driver.find_element(By.CSS_SELECTOR, ".ui-choose > li:nth-child(5)").click()
        # 20 | click | css=tr:nth-child(9) > td:nth-child(8) | 
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) > td:nth-child(8)").click()
        # 21 | click | css=tr:nth-child(9) > td:nth-child(5) | 
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) > td:nth-child(5)").click()
        # 22 | click | css=tr:nth-child(9) .btn-add-course | 
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) .btn-add-course").click()
        # 23 | click | css=.captcha | 
        self.driver.find_element(By.CSS_SELECTOR, ".captcha").click()
        # 24 | click | id=cos_qry_confirm_validation_code | 
        self.driver.find_element(By.ID, "cos_qry_confirm_validation_code").click()
        # 25 | type | id=cos_qry_confirm_validation_code | 3C00
        self.driver.find_element(By.ID, "cos_qry_confirm_validation_code").send_keys("3C00")
        # 26 | click | css=.addcourse_confirm_save_button | 
        self.driver.find_element(By.CSS_SELECTOR, ".addcourse_confirm_save_button").click()
        # 27 | click | css=#error_msg .modal-body | 
        self.driver.find_element(By.CSS_SELECTOR, "#error_msg .modal-body").click()
        # 28 | click | css=#error_msg .btn | 
        self.driver.find_element(By.CSS_SELECTOR, "#error_msg .btn").click()
    
